import base64
import json
import os
import re
from datetime import datetime

import requests
import streamlit as st


# ============================================================
# KINGSBOT AI
# ============================================================

APP_NAME = "KingsBot AI"

CHAT_MODEL = "Qwen/Qwen2.5-7B-Instruct"
WHISPER_MODEL = "openai/whisper-large-v3"
TTS_MODEL = "facebook/mms-tts-eng"

MEMORY_FILE = "kingsbot_memory.json"

NOW = datetime.now()
CURRENT_DATE = NOW.strftime("%B %d, %Y")
CURRENT_YEAR = NOW.year


# ============================================================
# PAGE
# ============================================================

st.set_page_config(
    page_title=APP_NAME,
    page_icon="🤖",
    layout="centered"
)


# ============================================================
# HF TOKEN
# ============================================================

try:
    HF_TOKEN = st.secrets.get("HF_TOKEN", "")
except Exception:
    HF_TOKEN = os.environ.get("HF_TOKEN", "")


# ============================================================
# MEMORY
# ============================================================

def default_memory():
    return {
        "name": None,
        "education_level": None,
        "facts": [],
        "preferences": []
    }


def load_memory():
    memory = default_memory()

    try:
        if os.path.exists(MEMORY_FILE):
            with open(
                MEMORY_FILE,
                "r",
                encoding="utf-8"
            ) as file:
                saved = json.load(file)

            if isinstance(saved, dict):
                for key in memory:
                    if key in saved:
                        memory[key] = saved[key]

    except Exception:
        pass

    return memory


def save_memory():
    memory = {
        "name": st.session_state.name,
        "education_level": st.session_state.education_level,
        "facts": st.session_state.facts[-50:],
        "preferences": st.session_state.preferences[-30:]
    }

    try:
        with open(
            MEMORY_FILE,
            "w",
            encoding="utf-8"
        ) as file:
            json.dump(
                memory,
                file,
                indent=2,
                ensure_ascii=False
            )
    except Exception:
        pass


saved = load_memory()


# ============================================================
# SESSION STATE
# ============================================================

defaults = {
    "messages": [],
    "name": saved["name"],
    "education_level": saved["education_level"],
    "facts": saved["facts"],
    "preferences": saved["preferences"],
    "emotion": "neutral",
    "tone": "Normal",
    "topic": "general knowledge",
    "source": "KingsBot AI",
    "confidence": "Medium",
    "reason": "Generated by KingsBot.",
    "voice_enabled": True,
    "auto_speak": True,
    "voice_speed": "Normal"
}

for key, value in defaults.items():
    if key not in st.session_state:
        st.session_state[key] = value


# ============================================================
# API HELPERS
# ============================================================

def has_token():
    return bool(
        HF_TOKEN and
        HF_TOKEN.strip()
    )


def hf_headers(content_type=None):
    headers = {
        "Authorization": f"Bearer {HF_TOKEN}"
    }

    if content_type:
        headers["Content-Type"] = content_type

    return headers


# ============================================================
# PERSONAL MEMORY
# ============================================================

def remember_information(text):
    name_match = re.search(
        r"\b(?:my name is|call me)\s+([A-Za-z][A-Za-z '\-]{1,39})",
        text,
        re.IGNORECASE
    )

    if name_match:
        st.session_state.name = (
            name_match.group(1).strip()
        )
        save_memory()


    fact_match = re.search(
        r"\b(?:remember that|remember this|save this)"
        r"\s*[:,-]?\s*(.+)",
        text,
        re.IGNORECASE
    )

    if fact_match:
        fact = fact_match.group(1).strip()

        if fact and fact not in st.session_state.facts:
            st.session_state.facts.append(fact)

        st.session_state.facts = (
            st.session_state.facts[-50:]
        )

        save_memory()

        return fact

    return None


# ============================================================
# ETHICAL FORGETTING
# ============================================================

def forget_information(text):
    low = text.lower()

    if (
        "forget everything" in low
        or "forget all my memory" in low
        or "delete all my memory" in low
    ):
        st.session_state.name = None
        st.session_state.education_level = None
        st.session_state.facts = []
        st.session_state.preferences = []

        save_memory()

        return (
            "Done. I cleared your saved personal memory."
        )


    if (
        "forget my name" in low
        or "delete my name" in low
    ):
        st.session_state.name = None
        save_memory()

        return (
            "Done. I forgot your saved name."
        )


    if (
        "forget my class" in low
        or "forget my education level" in low
    ):
        st.session_state.education_level = None
        save_memory()

        return (
            "Done. I forgot your saved education level."
        )


    return None


# ============================================================
# EDUCATION LEVELS
# ============================================================

EDUCATION_LEVELS = {
    "Primary 1": ["primary 1", "primary one", "pry 1"],
    "Primary 2": ["primary 2", "primary two", "pry 2"],
    "Primary 3": ["primary 3", "primary three", "pry 3"],
    "Primary 4": ["primary 4", "primary four", "pry 4"],
    "Primary 5": ["primary 5", "primary five", "pry 5"],
    "Primary 6": ["primary 6", "primary six", "pry 6"],
    "JSS1": ["jss1", "jss 1", "jss one"],
    "JSS2": ["jss2", "jss 2", "jss two"],
    "JSS3": ["jss3", "jss 3", "jss three"],
    "SS1": ["ss1", "ss 1", "ss one", "sss1", "sss 1"],
    "SS2": ["ss2", "ss 2", "ss two", "sss2", "sss 2"],
    "SS3": ["ss3", "ss 3", "ss three", "sss3", "sss 3"],
    "University": [
        "university",
        "undergraduate",
        "college"
    ]
}


def detect_education(text):
    low = text.lower()

    for level, names in EDUCATION_LEVELS.items():
        if any(name in low for name in names):
            st.session_state.education_level = level
            save_memory()
            return level

    return None


# ============================================================
# EMOTIONAL INTELLIGENCE
# ============================================================

def detect_emotion(text):
    low = text.lower()

    if any(
        word in low
        for word in [
            "angry",
            "mad",
            "annoyed",
            "frustrated",
            "mistake",
            "wrong"
        ]
    ):
        return "frustrated"


    if any(
        word in low
        for word in [
            "sad",
            "crying",
            "hurt",
            "upset"
        ]
    ):
        return "sad"


    if any(
        word in low
        for word in [
            "confused",
            "don't understand",
            "do not understand"
        ]
    ):
        return "confused"


    if any(
        word in low
        for word in [
            "worried",
            "scared",
            "afraid",
            "nervous"
        ]
    ):
        return "worried"


    if any(
        word in low
        for word in [
            "happy",
            "great",
            "awesome",
            "thanks",
            "thank you",
            "yess"
        ]
    ):
        return "happy"


    return "neutral"


# ============================================================
# TONE ADAPTATION
# ============================================================

def select_tone(emotion):
    tones = {
        "frustrated": "Calm",
        "sad": "Supportive",
        "confused": "Simple",
        "worried": "Reassuring",
        "happy": "Friendly",
        "neutral": "Normal"
    }

    return tones.get(
        emotion,
        "Normal"
    )


def tone_instruction(tone):
    instructions = {
        "Normal": "Speak naturally, clearly, and conversationally.",
        "Calm": "Be calm, patient, and direct.",
        "Supportive": "Be warm, kind, and supportive.",
        "Simple": "Use simple language and explain step by step.",
        "Reassuring": "Be reassuring and practical.",
        "Friendly": "Be friendly and positive."
    }

    return instructions.get(
        tone,
        instructions["Normal"]
    )


# ============================================================
# PATTERN RECOGNITION
# ============================================================

def detect_topic(text):
    low = text.lower()

    topics = {
        "coding": [
            "code",
            "python",
            "programming",
            "streamlit",
            "app"
        ],
        "mathematics": [
            "math",
            "calculate",
            "equation",
            "algebra",
            "geometry",
            "calculus"
        ],
        "science": [
            "science",
            "biology",
            "chemistry",
            "physics"
        ],
        "sports": [
            "football",
            "soccer",
            "world cup",
            "messi",
            "fifa"
        ],
        "education": [
            "school",
            "class",
            "jss",
            "sss",
            "primary",
            "university"
        ],
        "history": [
            "history",
            "historical",
            "war",
            "empire"
        ],
        "geography": [
            "country",
            "capital",
            "continent",
            "geography"
        ],
        "technology": [
            "technology",
            "computer",
            "phone",
            "internet",
            "ai"
        ],
        "entertainment": [
            "movie",
            "film",
            "actor",
            "music",
            "song"
        ]
    }

    for topic, words in topics.items():
        if any(word in low for word in words):
            return topic

    return "general knowledge"


# ============================================================
# CURRENT INFORMATION
# ============================================================

def needs_current_information(text):
    low = text.lower()

    return any(
        word in low
        for word in [
            "today",
            "currently",
            "right now",
            "latest",
            "recent",
            "this year",
            "this month",
            "this week",
            "2026",
            "news"
        ]
    )


def current_lookup(question):
    try:
        response = requests.get(
            "https://en.wikipedia.org/w/api.php",
            params={
                "action": "query",
                "list": "search",
                "srsearch": question,
                "format": "json",
                "utf8": "1",
                "srlimit": 3
            },
            headers={
                "User-Agent": "KingsBotAI/1.0"
            },
            timeout=10
        )

        response.raise_for_status()

        results = (
            response.json()
            .get("query", {})
            .get("search", [])
        )

        information = []

        for item in results:
            title = item.get("title")

            if not title:
                continue

            try:
                page = requests.get(
                    "https://en.wikipedia.org/api/rest_v1/page/summary/"
                    + requests.utils.quote(title),
                    headers={
                        "User-Agent": "KingsBotAI/1.0"
                    },
                    timeout=10
                )

                if page.ok:
                    summary = page.json().get(
                        "extract"
                    )

                    if summary:
                        information.append(
                            f"{title}: {summary}"
                        )

            except Exception:
                continue

        if information:
            return "\n\n".join(
                information[:3]
            )

    except Exception:
        pass

    return None


# ============================================================
# SYSTEM PROMPT
# ============================================================

def build_system_prompt(retrieved=None):
    memory_lines = []

    if st.session_state.name:
        memory_lines.append(
            "User name: "
            + st.session_state.name
        )

    if st.session_state.education_level:
        memory_lines.append(
            "Education level: "
            + st.session_state.education_level
        )

    for fact in st.session_state.facts[-20:]:
        memory_lines.append(
            "Saved fact: "
            + fact
        )

    if not memory_lines:
        memory_lines.append(
            "No saved personal information."
        )


    retrieved_text = ""

    if retrieved:
        retrieved_text = (
            "\nCURRENT RETRIEVED INFORMATION:\n"
            + retrieved
            + "\n"
        )


    return f"""
You are KingsBot AI.

CURRENT DATE:
Today is {CURRENT_DATE}.
The current year is {CURRENT_YEAR}.
Never incorrectly describe 2026 as the future
when the current date is in 2026.

GENERAL KNOWLEDGE:
Answer questions about mathematics, science,
history, geography, countries, people, culture,
technology, computers, space, animals, languages,
literature, entertainment, sports, education,
and everyday life.

Do not invent facts.
If you are uncertain, say so.

PERSONAL MEMORY:
{chr(10).join(memory_lines)}

EDUCATION:
Support Primary 1 through Primary 6,
JSS1 through JSS3,
SS1 through SS3,
and University.

Match the explanation to the user's level
when that information is available.

EMOTIONAL INTELLIGENCE:
Detected emotion: {st.session_state.emotion}

TONE:
{st.session_state.tone}

{tone_instruction(st.session_state.tone)}

PROACTIVE GLUE:
Understand what the user is trying to accomplish.
Connect relevant information from the conversation.
Only make suggestions when they are useful.

PATTERN RECOGNITION:
Current topic: {st.session_state.topic}

MULTI-STEP REASONING:
For complicated questions, work through the problem
carefully and check the result.
Do not reveal private chain-of-thought.

RADICAL TRANSPARENCY:
Do not pretend to know something you do not know.
Clearly distinguish model knowledge from retrieved
information and uncertainty.

CODING:
When helping with code, check indentation,
imports, syntax, variable names, and logic.
When asked for complete code, provide complete code.

VOICE:
Write naturally so that the response sounds good
when spoken aloud.

Answer the user's question directly.
{retrieved_text}
"""


# ============================================================
# AI CHAT
# ============================================================

def ask_ai(user_text, retrieved=None):
    if not has_token():
        st.session_state.source = "AI connection"
        st.session_state.confidence = "Unavailable"
        st.session_state.reason = (
            "HF_TOKEN has not been added to the Space Secrets."
        )

        return (
            "KingsBot is loaded, but its AI brain is not connected yet. "
            "Add HF_TOKEN to your Hugging Face Space Secrets."
        )


    messages = [
        {
            "role": "system",
            "content": build_system_prompt(
                retrieved
            )
        }
    ]


    messages.extend(
        st.session_state.messages[-12:]
    )


    messages.append(
        {
            "role": "user",
            "content": user_text
        }
    )


    payload = {
        "model": CHAT_MODEL,
        "messages": messages,
        "temperature": 0.6,
        "max_tokens": 700
    }


    try:
        response = requests.post(
            "https://router.huggingface.co/v1/chat/completions",
            headers=hf_headers(
                "application/json"
            ),
            json=payload,
            timeout=120
        )

        response.raise_for_status()

        data = response.json()

        choices = data.get(
            "choices",
            []
        )

        if not choices:
            raise ValueError(
                "The AI returned no answer."
            )

        answer = (
            choices[0]
            .get("message", {})
            .get("content", "")
            .strip()
        )

        if not answer:
            raise ValueError(
                "The AI returned an empty answer."
            )


        if retrieved:
            st.session_state.source = (
                "AI model + current information"
            )
            st.session_state.confidence = "Medium-High"
            st.session_state.reason = (
                "Additional retrieved information "
                "was supplied to the AI."
            )

        else:
            st.session_state.source = (
                "AI model + memory + conversation"
            )
            st.session_state.confidence = "Medium"
            st.session_state.reason = (
                "Generated by the AI using conversation "
                "and saved memory."
            )


        return answer


    except requests.exceptions.Timeout:
        st.session_state.confidence = "Low"
        st.session_state.reason = (
            "The AI service timed out."
        )

        return (
            "The AI service took too long to respond. "
            "Please try again."
        )


    except requests.exceptions.HTTPError:
        st.session_state.confidence = "Low"
        st.session_state.reason = (
            "The AI service returned an HTTP error."
        )

        try:
            details = response.json()
            message = json.dumps(
                details,
                indent=2
            )
        except Exception:
            message = response.text

        return (
            "The AI service returned an error:\n\n"
            + message
        )


    except Exception as error:
        st.session_state.confidence = "Low"
        st.session_state.reason = (
            "An unexpected AI error occurred."
        )

        return (
            "KingsBot encountered an error:\n\n"
            + str(error)
        )


# ============================================================
# SPEECH TO TEXT
# ============================================================

def speech_to_text(audio_file):
    if not has_token():
        return None, (
            "Voice recognition needs HF_TOKEN."
        )


    try:
        audio_bytes = audio_file.getvalue()

        response = requests.post(
            "https://router.huggingface.co/hf-inference/models/"
            + WHISPER_MODEL,
            headers=hf_headers(
                "audio/wav"
            ),
            data=audio_bytes,
            timeout=120
        )

        response.raise_for_status()

        data = response.json()

        if isinstance(data, dict):
            text = data.get("text")

            if text:
                return text.strip(), None


        return None, (
            "I could not understand the recording."
        )


    except Exception as error:
        return None, (
            "Voice recognition failed: "
            + str(error)
        )


# ============================================================
# TEXT TO SPEECH
# ============================================================

def text_to_speech(text):
    if not has_token():
        return None


    try:
        response = requests.post(
            "https://router.huggingface.co/hf-inference/models/"
            + TTS_MODEL,
            headers=hf_headers(
                "application/json"
            ),
            json={
                "inputs": text[:2500]
            },
            timeout=120
        )

        response.raise_for_status()

        return response.content


    except Exception:
        return None


# ============================================================
# CONVERSATION FILE
# ============================================================

def conversation_text():
    lines = [
        "KINGSBOT AI CONVERSATION",
        "=" * 50,
        f"Date: {CURRENT_DATE}",
        ""
    ]

    for message in st.session_state.messages:
        role = (
            "YOU"
            if message["role"] == "user"
            else "KINGSBOT"
        )

        lines.append(
            role + ":"
        )

        lines.append(
            message["content"]
        )

        lines.append(
            "-" * 50
        )

    return "\n".join(lines)


# ============================================================
# TITLE
# ============================================================

st.title(
    "🤖 KingsBot AI"
)

st.caption(
    "AI Brain • General Knowledge • Memory • "
    "EQ • Reasoning • Voice"
)


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.header(
        "⚙️ Settings"
    )


    st.subheader(
        "🎤 Voice Assistant"
    )


    st.session_state.voice_enabled = st.toggle(
        "Voice assistant",
        value=st.session_state.voice_enabled
    )


    st.session_state.auto_speak = st.toggle(
        "Speak answers automatically",
        value=st.session_state.auto_speak
    )


    st.session_state.voice_speed = st.selectbox(
        "Voice speed",
        [
            "Slow",
            "Normal",
            "Fast"
        ],
        index=1
    )


    st.caption(
        "Default: Normal"
    )


    st.divider()


    st.subheader(
        "👤 Personal Memory"
    )


    st.write(
        "Name:",
        st.session_state.name
        or "Not saved"
    )


    st.write(
        "Education:",
        st.session_state.education_level
        or "Not saved"
    )


    st.write(
        "Saved facts:",
        len(st.session_state.facts)
    )


    st.divider()


    st.subheader(
        "❤️ Emotional Intelligence"
    )


    st.write(
        "Emotion:",
        st.session_state.emotion
    )


    st.write(
        "Tone:",
        st.session_state.tone
    )


    st.divider()


    st.subheader(
        "🧩 Pattern Recognition"
    )


    st.write(
        "Topic:",
        st.session_state.topic
    )


    st.divider()


    st.subheader(
        "🔍 Radical Transparency"
    )


    st.write(
        "Source:",
        st.session_state.source
    )


    st.write(
        "Confidence:",
        st.session_state.confidence
    )


    st.caption(
        st.session_state.reason
    )


    st.divider()


    if st.session_state.messages:

        st.download_button(
            "💾 Save conversation",
            conversation_text(),
            "kingsbot_conversation.txt",
            "text/plain"
        )


    if st.button(
        "🗑️ Clear conversation"
    ):
        st.session_state.messages = []
        st.rerun()


    if st.button(
        "🧹 Forget personal memory"
    ):
        st.session_state.name = None
        st.session_state.education_level = None
        st.session_state.facts = []
        st.session_state.preferences = []

        save_memory()

        st.rerun()


# ============================================================
# CHAT HISTORY
# ============================================================

for message in st.session_state.messages:

    with st.chat_message(
        message["role"]
    ):
        st.markdown(
            message["content"]
        )


# ============================================================
# VOICE INPUT
# ============================================================

voice_prompt = None


if st.session_state.voice_enabled:

    st.subheader(
        "🎤 Talk to KingsBot"
    )


    audio_file = st.audio_input(
        "Tap the microphone and speak"
    )


    if audio_file:

        with st.spinner(
            "🎧 Understanding your voice..."
        ):
            voice_prompt, voice_error = (
                speech_to_text(
                    audio_file
                )
            )


        if voice_prompt:
            st.success(
                "You said: "
                + voice_prompt
            )

        elif voice_error:
            st.error(
                voice_error
            )


# ============================================================
# TEXT INPUT
# ============================================================

text_prompt = st.chat_input(
    "Ask KingsBot anything..."
)


prompt = (
    voice_prompt
    if voice_prompt
    else text_prompt
)


# ============================================================
# PROCESS MESSAGE
# ============================================================

if prompt:

    remember_information(
        prompt
    )

    detect_education(
        prompt
    )


    forgotten = forget_information(
        prompt
    )


    st.session_state.emotion = (
        detect_emotion(
            prompt
        )
    )


    st.session_state.tone = (
        select_tone(
            st.session_state.emotion
        )
    )


    st.session_state.topic = (
        detect_topic(
            prompt
        )
    )


    with st.chat_message(
        "user"
    ):
        st.markdown(
            prompt
        )


    with st.chat_message(
        "assistant"
    ):

        if forgotten:

            answer = forgotten

            st.session_state.source = (
                "KingsBot memory system"
            )

            st.session_state.confidence = "High"

            st.session_state.reason = (
                "The user explicitly requested "
                "a memory change."
            )

        else:

            retrieved = None


            if needs_current_information(
                prompt
            ):

                with st.spinner(
                    "🔎 Checking current information..."
                ):
                    retrieved = current_lookup(
                        prompt
                    )


            with st.spinner(
                "🧠 Thinking..."
            ):
                answer = ask_ai(
                    prompt,
                    retrieved
                )


        st.markdown(
            answer
        )


        st.caption(
            "🔎 Source: "
            + st.session_state.source
        )


        st.caption(
            "📊 Confidence: "
            + st.session_state.confidence
        )


        st.caption(
            "ℹ️ "
            + st.session_state.reason
        )


        # ====================================================
        # VOICE RESPONSE
        # ====================================================

        if (
            st.session_state.voice_enabled
            and st.session_state.auto_speak
            and has_token()
        ):

            with st.spinner(
                "🔊 Speaking..."
            ):

                speech = text_to_speech(
                    answer
                )


            if speech:
                st.audio(
                    speech,
                    format="audio/wav"
                )


    st.session_state.messages.append(
        {
            "role": "user",
            "content": prompt
        }
    )


    st.session_state.messages.append(
        {
            "role": "assistant",
            "content": answer
        }
    )

"requirements.txt"

streamlit
requests

One thing you must have: "HF_TOKEN" in your Hugging Face Space's Settings → Secrets. Without that, the interface can load, but the online AI brain and voice models cannot answer.

Also, I did not hard-code answers such as a Spider-Man movie or Messi's World Cup count into the brain. KingsBot should retrieve/check facts rather than pretending every fact is permanently stored in the code.
