import io
import json
import os
import re

import requests
import streamlit as st
import speech_recognition as sr
from gtts import gTTS
from groq import Groq


# ============================================================
# KINGSBOT AI - COMPLETE UPGRADED VERSION
# ============================================================

MODEL_NAME = "openai/gpt-oss-20b"
CURRENT_DATE = "August 26, 2026"
MEMORY_FILE = "kingsbot_memory.json"

st.set_page_config(
    page_title="KingsBot AI",
    page_icon="🤖",
    layout="centered",
)


# ============================================================
# MEMORY
# ============================================================

def default_memory():
    return {
        "name": None,
        "education_level": None,
        "facts": [],
        "preferences": [],
        "topics": [],
    }


def load_memory():
    data = default_memory()

    try:
        if os.path.exists(MEMORY_FILE):
            with open(MEMORY_FILE, "r", encoding="utf-8") as file:
                saved = json.load(file)

            if isinstance(saved, dict):
                for key in data:
                    if key in saved:
                        data[key] = saved[key]
    except Exception:
        pass

    return data


saved = load_memory()


def save_memory():
    data = {
        "name": st.session_state.user_name,
        "education_level": st.session_state.student_level,
        "facts": st.session_state.personal_memory,
        "preferences": st.session_state.preferences,
        "topics": st.session_state.topic_pattern,
    }

    try:
        with open(MEMORY_FILE, "w", encoding="utf-8") as file:
            json.dump(data, file, indent=2, ensure_ascii=False)
    except Exception:
        pass


# ============================================================
# SESSION STATE
# ============================================================

defaults = {
    "messages": [],
    "user_name": saved["name"],
    "student_level": saved["education_level"],
    "personal_memory": saved["facts"],
    "preferences": saved["preferences"],
    "topic_pattern": saved["topics"],
    "emotion": "neutral",
    "tone": "Natural and friendly",
    "confidence": "Medium",
    "source": "Groq " + MODEL_NAME,
    "reason": "Generated by the OpenAI cloud model.",
    "last_topic": "general knowledge",
    "last_user_question": "",
    "last_response": "",
}

for key, value in defaults.items():
    if key not in st.session_state:
        st.session_state[key] = value


# ============================================================
# MODEL / GROQ BRAIN
# ============================================================

def get_groq_client():
    try:
        api_key = st.secrets.get("GROQ_API_KEY")
    except Exception:
        api_key = None

    if not api_key:
        return None

    return Groq(api_key=api_key)


client = get_groq_client()

if client is None:
    st.error(
        "KingsBot cannot find GROQ_API_KEY in Streamlit Secrets. "
        "Add the key there and save the app."
    )
    st.stop()


# ============================================================
# EMOTION + TONE
# ============================================================

def detect_emotion(text):
    lower = text.lower()

    groups = {
        "frustrated": [
            "angry",
            "mad",
            "annoyed",
            "frustrated",
            "you are wrong",
            "mistake",
            "this is wrong",
        ],
        "sad": ["sad", "crying", "upset", "hurt", "unhappy"],
        "confused": [
            "confused",
            "don't understand",
            "do not understand",
            "explain again",
            "i don't get it",
        ],
        "worried": [
            "worried",
            "scared",
            "afraid",
            "nervous",
            "anxious",
        ],
        "excited": [
            "excited",
            "amazing",
            "wow",
            "can't wait",
        ],
        "happy": [
            "happy",
            "great",
            "awesome",
            "thanks",
            "thank you",
            "yesss",
        ],
    }

    for emotion, words in groups.items():
        if any(word in lower for word in words):
            return emotion

    return "neutral"


def tone_for(emotion):
    tones = {
        "frustrated": (
            "Calm and direct",
            "Be calm, respectful, direct, and acknowledge frustration.",
        ),
        "sad": (
            "Warm and supportive",
            "Be kind, warm, and supportive without pretending to have human feelings.",
        ),
        "confused": (
            "Simple and step-by-step",
            "Use simple words, examples, and numbered steps when useful.",
        ),
        "worried": (
            "Reassuring and practical",
            "Be reassuring, careful, realistic, and practical.",
        ),
        "excited": (
            "Energetic and positive",
            "Match the user's excitement while staying accurate.",
        ),
        "happy": (
            "Friendly and positive",
            "Be friendly, positive, and energetic.",
        ),
        "neutral": (
            "Natural and friendly",
            "Be natural, friendly, clear, and concise.",
        ),
    }

    return tones.get(emotion, tones["neutral"])


# ============================================================
# TOPIC RECOGNITION
# ============================================================

TOPIC_KEYWORDS = {
    "coding": [
        "code", "python", "program", "programming", "streamlit",
        "app", "software", "javascript", "html", "css", "github",
    ],
    "mathematics": [
        "math", "calculate", "equation", "algebra", "geometry",
        "calculus", "percentage", "fraction", "multiply", "divide",
    ],
    "science": [
        "science", "biology", "chemistry", "physics", "experiment",
        "atom", "cell", "energy",
    ],
    "sports": [
        "football", "soccer", "world cup", "player", "messi",
        "ronaldo", "basketball", "tennis",
    ],
    "education": [
        "school", "class", "jss", "sss", "primary", "university",
        "exam", "lesson", "homework",
    ],
    "history": [
        "history", "historical", "war", "empire", "ancient",
        "kingdom", "president",
    ],
    "geography": [
        "country", "capital", "continent", "geography", "river",
        "mountain", "ocean", "city",
    ],
    "technology": [
        "technology", "computer", "phone", "internet", "ai",
        "artificial intelligence", "android",
    ],
    "entertainment": [
        "movie", "film", "actor", "actress", "music", "song",
        "singer", "game", "gaming",
    ],
    "business": [
        "business", "company", "money", "startup", "customer",
        "marketing", "selling",
    ],
    "health": [
        "health", "body", "exercise", "food", "sleep",
    ],
    "general knowledge": [
        "who is", "what is", "where is", "when did", "why is",
        "how does", "tell me about", "meaning of",
    ],
}


def recognize_topic(text):
    lower = text.lower()

    best_topic = "general knowledge"
    best_score = 0

    for topic, words in TOPIC_KEYWORDS.items():
        score = sum(1 for word in words if word in lower)

        if score > best_score:
            best_score = score
            best_topic = topic

    return best_topic


def update_topic(text):
    topic = recognize_topic(text)
    st.session_state.last_topic = topic

    if topic not in st.session_state.topic_pattern:
        st.session_state.topic_pattern.append(topic)
        st.session_state.topic_pattern = (
            st.session_state.topic_pattern[-30:]
        )
        save_memory()

    return topic


# ============================================================
# VERIFIED FACTS
# ============================================================

def verified_fact(question):
    lower = question.lower()

    if "messi" in lower and "world cup" in lower:
        return (
            "Lionel Messi has won the FIFA World Cup once, "
            "with Argentina at the 2022 FIFA World Cup."
        )

    if (
        "what year is it" in lower
        or "which year is it" in lower
        or "current year" in lower
    ):
        return "The current year is 2026."

    if (
        "today's date" in lower
        or "todays date" in lower
        or "what date is it" in lower
    ):
        return "Today is August 26, 2026."

    if (
        ("spider-man" in lower or "spiderman" in lower)
        and "2026" in lower
    ):
        return (
            "The Spider-Man film scheduled for 2026 is "
            "Spider-Man: Brand New Day."
        )

    return None


# ============================================================
# CURRENT INFORMATION
# ============================================================

def needs_current_lookup(text):
    lower = text.lower()

    return any(
        word in lower
        for word in [
            "today",
            "right now",
            "currently",
            "latest",
            "recent",
            "this year",
            "this month",
            "this week",
            "2026",
            "news",
        ]
    )


def current_lookup(question):
    try:
        response = requests.get(
            "https://en.wikipedia.org/w/api.php",
            params={
                "action": "query",
                "list": "search",
                "srsearch": question,
                "format": "json",
                "utf8": "1",
                "srlimit": 3,
            },
            headers={"User-Agent": "KingsBotAI/2.0"},
            timeout=8,
        )
        response.raise_for_status()

        results = []
        items = (
            response.json()
            .get("query", {})
            .get("search", [])
        )

        for item in items:
            title = item.get("title")

            if not title:
                continue

            try:
                page = requests.get(
                    "https://en.wikipedia.org/api/rest_v1/page/summary/"
                    + requests.utils.quote(title),
                    headers={"User-Agent": "KingsBotAI/2.0"},
                    timeout=8,
                )
                page.raise_for_status()

                summary = page.json().get("extract")

                if summary:
                    results.append(
                        title + ":\n" + summary
                    )

            except Exception:
                continue

        if results:
            return "\n\n".join(results[:3])

    except Exception:
        pass

    return None


# ============================================================
# CONTEXT
# ============================================================

def memory_context():
    items = []

    if st.session_state.user_name:
        items.append(
            "User's name: " + st.session_state.user_name
        )

    if st.session_state.student_level:
        items.append(
            "User's education level: "
            + st.session_state.student_level
        )

    for fact in st.session_state.personal_memory[-20:]:
        items.append("Saved user fact: " + fact)

    for preference in st.session_state.preferences[-10:]:
        items.append("User preference: " + preference)

    return "\n".join(items) if items else "No personal information is saved."


def education_context():
    if st.session_state.student_level:
        return (
            "The user's education level is "
            + st.session_state.student_level
            + ". Match educational explanations to that level. "
              "If the user requests advanced material, teach it at "
              "the requested level."
        )

    return (
        "The user's education level is unknown. "
        "Use a clear general explanation."
    )


def conversation_context():
    recent = st.session_state.messages[-10:]

    if not recent:
        return "No previous conversation."

    lines = []

    for message in recent:
        role = message.get("role", "user").upper()
        content = str(message.get("content", ""))
        lines.append(f"{role}: {content}")

    return "\n".join(lines)


# ============================================================
# PROACTIVE FOLLOW-UP QUESTION
# ============================================================

def should_ask_followup(text):
    lower = text.lower().strip()

    if len(lower) < 12:
        return False

    if lower.endswith("?"):
        return False

    return any(
        word in lower
        for word in [
            "tell me about",
            "explain",
            "teach me",
            "how",
            "why",
            "what",
            "learn",
        ]
    )


def add_proactive_instruction(prompt, user_message, topic):
    if not should_ask_followup(user_message):
        return prompt

    return (
        prompt
        + "\nPROACTIVE QUESTION:\n"
        + "After answering, you may ask ONE short, useful follow-up "
          "question related to the user's current topic. Do not ask "
          "a question every time. Never ask an unrelated question. "
          "Current topic: "
        + topic
        + ".\n\n"
    )


# ============================================================
# GENERATE RESPONSE
# ============================================================

def generate_response(user_message):
    detect_name(user_message)
    detect_student_level(user_message)
    remember_information(user_message)
    remember_preference(user_message)

    forgotten = forget_information(user_message)

    if forgotten:
        st.session_state.source = "KingsBot memory system"
        st.session_state.confidence = "High"
        st.session_state.reason = (
            "The user explicitly requested a memory change."
        )
        return forgotten

    emotion = detect_emotion(user_message)
    st.session_state.emotion = emotion

    tone_name, tone_instruction = tone_for(emotion)
    st.session_state.tone = tone_name

    topic = update_topic(user_message)

    fact = verified_fact(user_message)

    if fact:
        st.session_state.source = "KingsBot verified fact"
        st.session_state.confidence = "High"
        st.session_state.reason = (
            "A built-in factual safeguard matched the question."
        )
        return fact

    retrieved = None

    if needs_current_lookup(user_message):
        retrieved = current_lookup(user_message)

    prompt = (
        "You are KingsBot, a helpful AI assistant.\n\n"
        "CURRENT DATE:\n"
        "Today is August 26, 2026. The current year is 2026. "
        "Do not incorrectly call 2026 the future.\n\n"
        "GENERAL KNOWLEDGE:\n"
        "Answer broad questions about history, geography, countries, "
        "people, culture, technology, computers, mathematics, science, "
        "space, animals, languages, literature, entertainment, sports, "
        "education, business, coding, and everyday life. "
        "Do not invent facts. If uncertain, say so.\n\n"
        "MULTI-STEP REASONING:\n"
        "For difficult questions, break the task into useful steps, "
        "check calculations and code carefully, then provide the answer. "
        "Do not reveal private chain-of-thought.\n\n"
        "EDUCATION:\n"
        + education_context()
        + "\n\n"
        "EMOTIONAL INTELLIGENCE:\n"
        "Detected emotion: "
        + emotion
        + ". "
        + tone_instruction
        + "\n\n"
        "TONE ADAPTATION:\n"
        "Use the selected tone naturally. Do not announce the tone.\n\n"
        "CONTEXT AWARENESS:\n"
        "Use recent conversation when relevant. If the user changes "
        "topic, follow the new topic.\n\n"
        "PATTERN RECOGNITION:\n"
        "Current topic: "
        + topic
        + ". Use recurring topics only when relevant.\n\n"
        "PERSONAL MEMORY:\n"
        + memory_context()
        + "\n\n"
        "RECENT CONVERSATION:\n"
        + conversation_context()
        + "\n\n"
    )

    if retrieved:
        prompt += (
            "CURRENT RETRIEVED INFORMATION:\n"
            + retrieved
            + "\n\n"
            "Use this information as evidence. "
            "Do not pretend it is your own memory.\n\n"
        )

    prompt = add_proactive_instruction(
        prompt,
        user_message,
        topic,
    )

    messages = [
        {
            "role": "user",
            "content": user_message,
        }
    ]

    for message in st.session_state.messages[-10:]:
        role = message.get("role")
        content = str(message.get("content", ""))
        if role in {"user", "assistant"} and content:
            messages.insert(-1, {
                "role": role,
                "content": content,
            })

    try:
        result = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[{"role": "system", "content": prompt}] + messages,
            temperature=0.5,
            top_p=0.9,
            max_completion_tokens=1200,
        )

        response = (result.choices[0].message.content or "").strip()

    except Exception as error:
        st.session_state.source = "Groq API error"
        st.session_state.confidence = "Unknown"
        st.session_state.reason = (
            "The cloud AI request failed. Check the API key, "
            "model access, rate limits, or internet connection."
        )
        return (
            "I couldn't reach my AI brain right now. "
            "Please check the Groq API key connection and try again.\n\n"
            "Technical detail: " + str(error)
        )

    if not response:
        response = "I couldn't generate an answer. Please try again."

    if retrieved:
        st.session_state.source = (
            "Groq + current information lookup"
        )
        st.session_state.confidence = "High"
        st.session_state.reason = (
            "The Groq model answered using the KingsBot context "
            "and retrieved current information when requested."
        )
    else:
        st.session_state.source = "Groq " + MODEL_NAME
        st.session_state.confidence = "High"
        st.session_state.reason = (
            "Generated by the Groq cloud model using KingsBot's "
            "memory, conversation context, topic recognition, "
            "education level, and tone instructions."
        )

    st.session_state.last_user_question = user_message
    st.session_state.last_response = response

    return response


# ============================================================
# SPEECH TO TEXT
# ============================================================

def speech_to_text(audio_file):
    try:
        recognizer = sr.Recognizer()

        audio_file.seek(0)

        with sr.AudioFile(audio_file) as source:
            audio_data = recognizer.record(source)

        if not audio_data:
            return None

        text = recognizer.recognize_google(
            audio_data,
            language="en-US",
        )

        return text.strip() if text else None

    except sr.UnknownValueError:
        return None

    except sr.RequestError:
        return None

    except Exception:
        return None


# ============================================================
# TEXT TO SPEECH
# ============================================================

def text_to_speech(text):
    try:
        audio = io.BytesIO()

        speech = gTTS(
            text=str(text)[:3000],
            lang="en",
            slow=False,
        )

        speech.write_to_fp(audio)
        audio.seek(0)

        return audio.getvalue()

    except Exception:
        return None


# ============================================================
# SAVE CONVERSATION
# ============================================================

def create_chat_file():
    lines = [
        "KINGSBOT AI - SAVED CONVERSATION",
        "=" * 50,
        "Date: " + CURRENT_DATE,
        "",
    ]

    if st.session_state.user_name:
        lines.append(
            "Name: " + st.session_state.user_name
        )

    if st.session_state.student_level:
        lines.append(
            "Education level: "
            + st.session_state.student_level
        )

    lines.extend(
        [
            "",
            "PERSONAL MEMORY",
            "-" * 40,
        ]
    )

    lines.extend(st.session_state.personal_memory)

    lines.extend(
        [
            "",
            "PREFERENCES",
            "-" * 40,
        ]
    )

    lines.extend(st.session_state.preferences)

    lines.extend(
        [
            "",
            "CONVERSATION",
            "=" * 50,
        ]
    )

    for message in st.session_state.messages:
        if message["role"] == "user":
            lines.append("YOU:")
        else:
            lines.append("KINGSBOT:")

        lines.append(message["content"])
        lines.extend(["", "-" * 50])

    return "\n".join(lines)


# ============================================================
# USER INTERFACE
# ============================================================

st.title("🤖 KingsBot AI")

st.caption(
    "AI • General Knowledge • Memory • EQ • "
    "Multi-Step Reasoning • Voice • 2026"
)


# ============================================================
# CONVERSATION
# ============================================================

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])


# ============================================================
# VOICE ASSISTANT
# ============================================================

st.subheader("🎤 Voice Assistant")

st.caption(
    "Tap the microphone, speak, then stop the recording. "
    "KingsBot will convert your voice to text and answer."
)

audio_file = st.audio_input(
    "🎙️ Record your message",
    sample_rate=16000,
    key="kingsbot_microphone",
)

voice_prompt = None

if audio_file:
    with st.spinner("🎧 Understanding your voice..."):
        voice_prompt = speech_to_text(audio_file)

    if voice_prompt:
        st.success("You said: " + voice_prompt)
    else:
        st.error(
            "I couldn't understand the recording. "
            "Check your microphone permission and try again."
        )


# ============================================================
# TEXT INPUT
# ============================================================

text_prompt = st.chat_input(
    "Ask KingsBot anything..."
)

prompt = voice_prompt or text_prompt


# ============================================================
# PROCESS MESSAGE
# ============================================================

if prompt:
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        with st.spinner("🧠 Thinking..."):
            try:
                response = generate_response(prompt)

            except Exception as error:
                response = (
                    "KingsBot encountered an error:\n\n"
                    + str(error)
                )

                st.session_state.source = "Error handler"
                st.session_state.confidence = "Unknown"
                st.session_state.reason = (
                    "An error occurred while processing the request."
                )

        st.markdown(response)

        st.caption(
            "🔎 Source: " + st.session_state.source
        )

        st.caption(
            "📊 Confidence: "
            + st.session_state.confidence
        )

        st.caption(
            "ℹ️ " + st.session_state.reason
        )

        with st.spinner("🔊 Preparing voice..."):
            audio = text_to_speech(response)

        if audio:
            try:
                st.audio(
                    audio,
                    format="audio/mp3",
                    autoplay=True,
                )
            except TypeError:
                # Compatibility fallback for older Streamlit versions.
                st.audio(
                    audio,
                    format="audio/mp3",
                )

    st.session_state.messages.append(
        {
            "role": "user",
            "content": prompt,
        }
    )

    st.session_state.messages.append(
        {
            "role": "assistant",
            "content": response,
        }
    )

    st.session_state.last_user_question = prompt
    st.session_state.last_response = response


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:
    st.header("🤖 KingsBot")

    st.subheader("👤 Personal Memory")

    st.write(
        "Name: "
        + (st.session_state.user_name or "Not saved")
    )

    st.write(
        "Class: "
        + (st.session_state.student_level or "Not saved")
    )

    st.write(
        "Saved facts: "
        + str(len(st.session_state.personal_memory))
    )

    st.write(
        "Preferences: "
        + str(len(st.session_state.preferences))
    )

    st.divider()

    st.subheader("📚 Conversation History")

    if st.session_state.messages:
        number = 0

        for message in st.session_state.messages:
            if message["role"] == "user":
                number += 1
                preview = message["content"]

                if len(preview) > 55:
                    preview = preview[:55] + "..."

                st.write(
                    f"💬 {number}. {preview}"
                )
    else:
        st.write("No conversations yet.")

    if st.session_state.messages:
        st.download_button(
            "💾 Save conversation",
            create_chat_file(),
            "kingsbot_conversation.txt",
            "text/plain",
        )

    st.divider()

    st.subheader("❤️ Emotional Intelligence")
    st.write(
        "Emotion: " + st.session_state.emotion
    )

    st.subheader("🎭 Tone Adaptation")
    st.write(st.session_state.tone)

    st.subheader("🔍 Radical Transparency")

    st.write(
        "Source: " + st.session_state.source
    )

    st.write(
        "Confidence: "
        + st.session_state.confidence
    )

    st.caption(st.session_state.reason)

    st.subheader("🧩 Pattern Recognition")

    st.write(
        "Current topic: "
        + st.session_state.last_topic
    )

    st.divider()

    st.subheader("Features")

    features = [
        "🧠 GPT-5.6 Luna cloud brain",
        "🌍 General knowledge",
        "📅 2026 awareness",
        "🔎 Current information lookup",
        "👤 Personal memory",
        "🧹 Ethical forgetting",
        "🎓 Primary → University",
        "❤️ Emotional intelligence",
        "🎭 Advanced tone adaptation",
        "🧩 Topic pattern recognition",
        "🧠 Multi-step reasoning",
        "💬 Conversation memory",
        "❓ Proactive follow-up questions",
        "🎤 Voice input",
        "🔊 Automatic voice output",
        "🧮 Mathematics",
        "💻 Coding",
        "📚 Education",
        "🔬 Science",
        "🌍 History and geography",
        "⚽ Sports",
        "🎬 Entertainment",
        "💼 Business",
        "💾 Save conversations",
        "🧠 Stronger cloud reasoning",
        "💻 Advanced coding help",
        "🧮 Advanced math help",
        "❓ Proactive follow-up questions",
    ]

    for feature in features:
        st.write(feature)

    st.divider()

    if st.button("🗑️ Clear conversation"):
        st.session_state.messages = []
        st.session_state.last_user_question = ""
        st.session_state.last_response = ""
        st.rerun()

    if st.button("🧹 Forget personal memory"):
        st.session_state.user_name = None
        st.session_state.student_level = None
        st.session_state.personal_memory = []
        st.session_state.preferences = []
        save_memory()

        st.success("Personal memory cleared.")
        st.rerun()

    st.divider()

    st.caption("Model: " + MODEL_NAME)
    st.caption("Groq API key is stored securely in Streamlit Secrets.")
