import io
import json
import os
import re
from datetime import datetime

import requests
import streamlit as st
import torch
import speech_recognition as sr
from gtts import gTTS
from transformers import AutoTokenizer, AutoModelForCausalLM


# ============================================================
# KINGSBOT AI
# ============================================================
# Real local language model
# Persistent personal memory
# Conversation memory
# Education-level memory
# EQ / sentiment
# Tone adaptation
# Proactive glue
# Pattern recognition
# Multi-step problem solving
# Radical transparency
# Current-information lookup
# Voice input + voice output
# Ethical forgetting
# Conversation saving
# No Hugging Face token required
# ============================================================

MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"

CURRENT_DATE = "August 25, 2026"
CURRENT_YEAR = 2026

MEMORY_FILE = "kingsbot_memory.json"


# ============================================================
# PAGE SETTINGS
# ============================================================

st.set_page_config(
    page_title="KingsBot AI",
    page_icon="🤖",
    layout="centered"
)


# ============================================================
# DEFAULT MEMORY
# ============================================================

DEFAULT_MEMORY = {
    "name": None,
    "education_level": None,
    "personal_facts": [],
    "preferences": [],
    "important_topics": []
}


# ============================================================
# LOAD PERSISTENT MEMORY
# ============================================================

def load_persistent_memory():

    try:

        if os.path.exists(MEMORY_FILE):

            with open(
                MEMORY_FILE,
                "r",
                encoding="utf-8"
            ) as file:

                data = json.load(file)

            if not isinstance(data, dict):

                return DEFAULT_MEMORY.copy()

            for key in DEFAULT_MEMORY:

                if key not in data:

                    data[key] = DEFAULT_MEMORY[key]

            return data

    except Exception:

        return DEFAULT_MEMORY.copy()


# ============================================================
# SAVE PERSISTENT MEMORY
# ============================================================

def save_persistent_memory():

    try:

        memory = {
            "name": st.session_state.user_name,
            "education_level": (
                st.session_state.student_level
            ),
            "personal_facts": (
                st.session_state.personal_memory
            ),
            "preferences": (
                st.session_state.preferences
            ),
            "important_topics": (
                st.session_state.topic_pattern
            )
        }

        with open(
            MEMORY_FILE,
            "w",
            encoding="utf-8"
        ) as file:

            json.dump(
                memory,
                file,
                indent=2,
                ensure_ascii=False
            )

        return True

    except Exception:

        return False


# ============================================================
# INITIALIZE MEMORY
# ============================================================

saved_memory = load_persistent_memory()


if "messages" not in st.session_state:

    st.session_state.messages = []


if "user_name" not in st.session_state:

    st.session_state.user_name = (
        saved_memory.get("name")
    )


if "student_level" not in st.session_state:

    st.session_state.student_level = (
        saved_memory.get("education_level")
    )


if "personal_memory" not in st.session_state:

    st.session_state.personal_memory = (
        saved_memory.get(
            "personal_facts",
            []
        )
    )


if "preferences" not in st.session_state:

    st.session_state.preferences = (
        saved_memory.get(
            "preferences",
            []
        )
    )


if "topic_pattern" not in st.session_state:

    st.session_state.topic_pattern = (
        saved_memory.get(
            "important_topics",
            []
        )
    )


if "emotion" not in st.session_state:

    st.session_state.emotion = "neutral"


if "tone" not in st.session_state:

    st.session_state.tone = (
        "Natural and friendly"
    )


if "confidence" not in st.session_state:

    st.session_state.confidence = "Medium"


if "source" not in st.session_state:

    st.session_state.source = (
        "KingsBot"
    )


if "reason" not in st.session_state:

    st.session_state.reason = (
        "Answer generated by KingsBot."
    )


if "last_topic" not in st.session_state:

    st.session_state.last_topic = None


# ============================================================
# LOAD MODEL
# ============================================================

@st.cache_resource(
    show_spinner="🧠 Loading KingsBot's brain..."
)
def load_model():

    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME
    )

    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        torch_dtype="auto",
        device_map="auto"
    )

    model.eval()

    return tokenizer, model


try:

    tokenizer, model = load_model()

except Exception as error:

    st.error(
        "KingsBot could not load its AI model."
    )

    st.code(str(error))

    st.stop()


# ============================================================
# NAME MEMORY
# ============================================================

def detect_name(text):

    patterns = [
        r"\bmy name is ([A-Za-z][A-Za-z '\-]{1,40})",
        r"\bcall me ([A-Za-z][A-Za-z '\-]{1,40})",
        r"\byou can call me ([A-Za-z][A-Za-z '\-]{1,40})"
    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            text,
            re.IGNORECASE
        )

        if match:

            name = match.group(1).strip()

            st.session_state.user_name = name

            save_persistent_memory()

            return name

    return None


# ============================================================
# EDUCATION MEMORY
# ============================================================

def detect_student_level(text):

    lower = text.lower()

    levels = {

        "PRIMARY 1": [
            "primary 1",
            "primary one",
            "pry 1"
        ],

        "PRIMARY 2": [
            "primary 2",
            "primary two",
            "pry 2"
        ],

        "PRIMARY 3": [
            "primary 3",
            "primary three",
            "pry 3"
        ],

        "PRIMARY 4": [
            "primary 4",
            "primary four",
            "pry 4"
        ],

        "PRIMARY 5": [
            "primary 5",
            "primary five",
            "pry 5"
        ],

        "PRIMARY 6": [
            "primary 6",
            "primary six",
            "pry 6"
        ],

        "JSS1": [
            "jss1",
            "jss 1",
            "jss one",
            "junior secondary 1"
        ],

        "JSS2": [
            "jss2",
            "jss 2",
            "jss two",
            "junior secondary 2"
        ],

        "JSS3": [
            "jss3",
            "jss 3",
            "jss three",
            "junior secondary 3"
        ],

        "SS1": [
            "ss1",
            "ss 1",
            "ss one",
            "sss1",
            "sss 1",
            "senior secondary 1"
        ],

        "SS2": [
            "ss2",
            "ss 2",
            "ss two",
            "sss2",
            "sss 2",
            "senior secondary 2"
        ],

        "SS3": [
            "ss3",
            "ss 3",
            "ss three",
            "sss3",
            "sss 3",
            "senior secondary 3"
        ],

        "UNIVERSITY": [
            "university",
            "undergraduate",
            "college"
        ]
    }

    for level, words in levels.items():

        for word in words:

            if word in lower:

                st.session_state.student_level = level

                save_persistent_memory()

                return level

    return None


# ============================================================
# EXPLICIT PERSONAL MEMORY
# ============================================================

def remember_information(text):

    lower = text.lower()

    triggers = [
        "remember that",
        "remember this",
        "please remember",
        "keep this in mind",
        "save this"
    ]

    for trigger in triggers:

        if trigger in lower:

            position = lower.find(trigger)

            memory = text[
                position + len(trigger):
            ].strip(" :,-")

            if memory:

                if memory not in (
                    st.session_state.personal_memory
                ):

                    st.session_state.personal_memory.append(
                        memory
                    )

                    save_persistent_memory()

                return memory

    return None


# ============================================================
# ETHICAL FORGETTING
# ============================================================

def forget_information(text):

    lower = text.lower()

    if (
        "forget everything" in lower
        or "forget all my memory" in lower
        or "delete all my memory" in lower
    ):

        st.session_state.user_name = None
        st.session_state.student_level = None
        st.session_state.personal_memory = []
        st.session_state.preferences = []

        save_persistent_memory()

        return (
            "Done. I cleared the personal information "
            "you asked me to forget."
        )

    if (
        "forget my name" in lower
        or "delete my name" in lower
    ):

        st.session_state.user_name = None

        save_persistent_memory()

        return (
            "Done. I forgot your saved name."
        )

    if (
        "forget my class" in lower
        or "forget my education level" in lower
    ):

        st.session_state.student_level = None

        save_persistent_memory()

        return (
            "Done. I forgot your saved education level."
        )

    return None


# ============================================================
# EMOTION / SENTIMENT
# ============================================================

def detect_emotion(text):

    lower = text.lower()

    if any(
        word in lower
        for word in [
            "angry",
            "mad",
            "annoyed",
            "frustrated",
            "you are wrong",
            "mistake"
        ]
    ):

        return "frustrated"

    if any(
        word in lower
        for word in [
            "sad",
            "crying",
            "upset",
            "hurt"
        ]
    ):

        return "sad"

    if any(
        word in lower
        for word in [
            "confused",
            "don't understand",
            "do not understand",
            "explain again"
        ]
    ):

        return "confused"

    if any(
        word in lower
        for word in [
            "worried",
            "scared",
            "afraid",
            "nervous"
        ]
    ):

        return "worried"

    if any(
        word in lower
        for word in [
            "happy",
            "great",
            "awesome",
            "thanks",
            "thank you",
            "yesss"
        ]
    ):

        return "happy"

    return "neutral"


# ============================================================
# TONE ADAPTATION
# ============================================================

def get_tone(emotion):

    if emotion == "frustrated":

        return (
            "Calm, respectful and direct.",
            "Calm and direct"
        )

    if emotion == "sad":

        return (
            "Warm, kind and supportive.",
            "Warm and supportive"
        )

    if emotion == "confused":

        return (
            "Simple, patient and step-by-step.",
            "Simple and step-by-step"
        )

    if emotion == "worried":

        return (
            "Reassuring, careful and practical.",
            "Reassuring and practical"
        )

    if emotion == "happy":

        return (
            "Friendly, positive and energetic.",
            "Friendly and positive"
        )

    return (
        "Natural, friendly and clear.",
        "Natural and friendly"
    )


# ============================================================
# PATTERN RECOGNITION
# ============================================================

def recognize_pattern(text):

    lower = text.lower()

    categories = {

        "coding": [
            "code",
            "python",
            "program",
            "programming",
            "streamlit",
            "app",
            "software"
        ],

        "mathematics": [
            "math",
            "calculate",
            "equation",
            "algebra",
            "geometry",
            "calculus"
        ],

        "science": [
            "science",
            "biology",
            "chemistry",
            "physics"
        ],

        "sports": [
            "football",
            "soccer",
            "world cup",
            "player",
            "messi"
        ],

        "education": [
            "school",
            "class",
            "jss",
            "sss",
            "primary",
            "university"
        ]
    }

    for category, words in categories.items():

        for word in words:

            if word in lower:

                return category

    return "general"


def update_pattern(text):

    topic = recognize_pattern(text)

    st.session_state.last_topic = topic

    if topic not in st.session_state.topic_pattern:

        st.session_state.topic_pattern.append(
            topic
        )

        save_persistent_memory()

    return topic


# ============================================================
# PROACTIVE GLUE THINKING
# ============================================================

def proactive_glue(text):

    topic = recognize_pattern(text)

    previous = st.session_state.last_topic

    if previous == topic:

        return (
            "The user appears to be continuing the "
            "same topic. Use relevant context from "
            "the recent conversation."
        )

    if previous and previous != topic:

        return (
            "The user appears to have changed topics. "
            "Focus on the new question and do not force "
            "unrelated previous information into the answer."
        )

    return (
        "Understand the user's actual goal. "
        "If there is an obvious useful next step, "
        "offer it briefly."
    )


# ============================================================
# MULTI-STEP REASONING
# ============================================================

def reasoning_instruction(text):

    topic = recognize_pattern(text)

    if topic == "mathematics":

        return (
            "Work through the mathematics carefully. "
            "Check arithmetic and logic before answering. "
            "Give the useful steps rather than guessing."
        )

    if topic == "coding":

        return (
            "Analyze the coding request first. "
            "Check imports, indentation, variables, "
            "functions and dependencies before producing code."
        )

    if topic == "education":

        return (
            "Identify the learner's education level. "
            "Teach progressively and do not accidentally "
            "replace a junior-school curriculum with "
            "university-level material."
        )

    return (
        "Analyze the question before answering. "
        "For multi-part problems, handle each important "
        "part logically. Do not expose private chain-of-thought."
    )


# ============================================================
# IMPORTANT FACT CHECKS
# ============================================================

def verified_fact(question):

    lower = question.lower()

    # Messi FIFA World Cup
    if (
        "messi" in lower
        and "world cup" in lower
    ):

        return (
            "Lionel Messi has won the FIFA World Cup "
            "once. He won it with Argentina at the "
            "2022 FIFA World Cup."
        )

    # Current year
    if (
        "what year is it" in lower
        or "which year is it" in lower
        or "current year" in lower
    ):

        return "The current year is 2026."

    # Current date
    if (
        "today's date" in lower
        or "todays date" in lower
        or "what date is it" in lower
    ):

        return (
            "Today is August 25, 2026."
        )

    return None


# ============================================================
# CURRENT INFORMATION DETECTION
# ============================================================

def needs_current_information(text):

    lower = text.lower()

    words = [
        "today",
        "right now",
        "currently",
        "latest",
        "recent",
        "recently",
        "this year",
        "this month",
        "this week",
        "2026",
        "news"
    ]

    return any(
        word in lower
        for word in words
    )


# ============================================================
# CURRENT INFORMATION LOOKUP
# ============================================================

def get_current_information(question):

    try:

        response = requests.get(
            "https://en.wikipedia.org/w/api.php",
            params={
                "action": "query",
                "list": "search",
                "srsearch": question,
                "format": "json",
                "utf8": "1",
                "srlimit": 3
            },
            headers={
                "User-Agent": "KingsBotAI/1.0"
            },
            timeout=8
        )

        response.raise_for_status()

        data = response.json()

        results = []

        for item in (
            data
            .get("query", {})
            .get("search", [])
        ):

            title = item.get("title")

            if not title:
                continue

            try:

                page = requests.get(
                    "https://en.wikipedia.org/api/rest_v1/page/summary/"
                    + requests.utils.quote(title),
                    headers={
                        "User-Agent": "KingsBotAI/1.0"
                    },
                    timeout=8
                )

                page.raise_for_status()

                summary = page.json().get(
                    "extract"
                )

                if summary:

                    results.append(
                        title
                        + ":\n"
                        + summary
                    )

            except Exception:

                continue

        if results:

            return "\n\n".join(
                results[:3]
            )

    except Exception:

        pass

    return None


# ============================================================
# MEMORY CONTEXT
# ============================================================

def build_memory_context():

    items = []

    if st.session_state.user_name:

        items.append(
            "User's name: "
            + st.session_state.user_name
        )

    if st.session_state.student_level:

        items.append(
            "User's education level: "
            + st.session_state.student_level
        )

    for fact in (
        st.session_state.personal_memory[-15:]
    ):

        items.append(
            "User explicitly asked KingsBot to remember: "
            + fact
        )

    if st.session_state.preferences:

        for preference in (
            st.session_state.preferences[-10:]
        ):

            items.append(
                "User preference: "
                + preference
            )

    if not items:

        return (
            "No personal information has been saved."
        )

    return "\n".join(items)


# ============================================================
# GENERATE RESPONSE
# ============================================================

def generate_response(user_message):

    # --------------------------------------------------------
    # MEMORY
    # --------------------------------------------------------

    detect_name(user_message)

    detect_student_level(user_message)

    remember_information(user_message)

    # --------------------------------------------------------
    # FORGETTING
    # --------------------------------------------------------

    forgotten = forget_information(
        user_message
    )

    if forgotten:

        st.session_state.source = (
            "KingsBot memory system"
        )

        st.session_state.confidence = "High"

        st.session_state.reason = (
            "The user explicitly requested "
            "a memory change."
        )

        return forgotten

    # --------------------------------------------------------
    # EQ
    # --------------------------------------------------------

    emotion = detect_emotion(
        user_message
    )

    st.session_state.emotion = emotion

    tone_text, tone_name = get_tone(
        emotion
    )

    st.session_state.tone = tone_name

    # --------------------------------------------------------
    # PATTERN
    # --------------------------------------------------------

    topic = update_pattern(
        user_message
    )

    # --------------------------------------------------------
    # PROACTIVE GLUE
    # --------------------------------------------------------

    glue = proactive_glue(
        user_message
    )

    # --------------------------------------------------------
    # REASONING
    # --------------------------------------------------------

    reasoning = reasoning_instruction(
        user_message
    )

    # --------------------------------------------------------
    # VERIFIED FACT
    # --------------------------------------------------------

    fact = verified_fact(
        user_message
    )

    if fact:

        st.session_state.source = (
            "KingsBot verified fact"
        )

        st.session_state.confidence = "High"

        st.session_state.reason = (
            "A specific built-in factual check "
            "matched this question."
        )

        return fact

    # --------------------------------------------------------
    # CURRENT INFORMATION
    # --------------------------------------------------------

    current_information = None

    if needs_current_information(
        user_message
    ):

        current_information = (
            get_current_information(
                user_message
            )
        )

    # --------------------------------------------------------
    # EDUCATION
    # --------------------------------------------------------

    if st.session_state.student_level:

        education = (
            "The user's current education level is "
            + st.session_state.student_level
            + ". Match educational answers to this level. "
            "Do not give university topics when the user "
            "asks for a junior or senior secondary syllabus."
        )

    else:

        education = (
            "The user's education level is unknown. "
            "Use a clear general explanation."
        )

    # --------------------------------------------------------
    # SYSTEM PROMPT
    # --------------------------------------------------------

    system_prompt = (

        "You are KingsBot, a helpful, intelligent "
        "and friendly AI assistant.\n\n"

        "DATE AWARENESS:\n"
        "Today is August 25, 2026.\n"
        "The current year is 2026.\n"
        "2026 is NOT the future. It is the current year.\n"
        "Years before 2026 are historical years.\n\n"

        "GENERAL KNOWLEDGE:\n"
        "You can discuss historical, scientific, "
        "educational, cultural, technological and "
        "everyday subjects across different time periods.\n\n"

        "FACTUAL ACCURACY:\n"
        "Do not invent facts. If you are uncertain, "
        "say so rather than confidently making up an answer.\n\n"

        "EDUCATION:\n"
        + education
        + "\n\n"

        "EMOTIONAL INTELLIGENCE:\n"
        "Detect the user's apparent emotional tone "
        "and respond appropriately.\n\n"

        "TONE:\n"
        + tone_text
        + "\n\n"

        "PROACTIVE GLUE:\n"
        + glue
        + "\n\n"

        "PATTERN RECOGNITION:\n"
        "Detected topic: "
        + topic
        + ".\n\n"

        "MULTI-STEP REASONING:\n"
        + reasoning
        + "\n\n"

        "PERSONAL MEMORY:\n"
        + build_memory_context()
    )

    # --------------------------------------------------------
    # CURRENT INFORMATION
    # --------------------------------------------------------

    if current_information:

        system_prompt += (

            "\n\nCURRENT RETRIEVED INFORMATION:\n"
            + current_information
            + "\n\n"

            "Use this information carefully. "
            "Do not claim that a source is live unless "
            "the information actually establishes that."
        )

    # --------------------------------------------------------
    # CONVERSATION
    # --------------------------------------------------------

    messages = [
        {
            "role": "system",
            "content": system_prompt
        }
    ]

    messages.extend(
        st.session_state.messages[-12:]
    )

    messages.append(
        {
            "role": "user",
            "content": user_message
        }
    )

    # --------------------------------------------------------
    # CHAT TEMPLATE
    # --------------------------------------------------------

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    # --------------------------------------------------------
    # TOKENIZE
    # --------------------------------------------------------

    model_inputs = tokenizer(
        [text],
        return_tensors="pt",
        truncation=True,
        max_length=2048
    ).to(model.device)

    # --------------------------------------------------------
    # GENERATE
    # --------------------------------------------------------

    with torch.no_grad():

        generated_ids = model.generate(
            **model_inputs,
            max_new_tokens=512,
            do_sample=True,
            temperature=0.6,
            top_p=0.9,
            repetition_penalty=1.05,
            pad_token_id=tokenizer.eos_token_id
        )

    # --------------------------------------------------------
    # REMOVE PROMPT
    # --------------------------------------------------------

    generated_ids = [

        output_ids[len(input_ids):]

        for input_ids, output_ids in zip(
            model_inputs.input_ids,
            generated_ids
        )
    ]

    # --------------------------------------------------------
    # DECODE
    # --------------------------------------------------------

    response = tokenizer.batch_decode(
        generated_ids,
        skip_special_tokens=True
    )[0].strip()

    if not response:

        response = (
            "I couldn't generate an answer. "
            "Please try again."
        )

    # --------------------------------------------------------
    # TRANSPARENCY
    # --------------------------------------------------------

    if current_information:

        st.session_state.source = (
            "Current lookup + Qwen"
        )

        st.session_state.confidence = (
            "Medium-High"
        )

        st.session_state.reason = (
            "KingsBot retrieved additional information "
            "before generating the response."
        )

    else:

        st.session_state.source = (
            "Qwen2.5-0.5B-Instruct"
        )

        st.session_state.confidence = (
            "Medium"
        )

        st.session_state.reason = (
            "Generated from the language model, "
            "conversation context and KingsBot's instructions."
        )

    return response


# ============================================================
# VOICE TO TEXT
# ============================================================

def speech_to_text(audio_file):

    recognizer = sr.Recognizer()

    try:

        audio_bytes = audio_file.getvalue()

        audio_source = sr.AudioFile(
            io.BytesIO(audio_bytes)
        )

        with audio_source as source:

            audio_data = recognizer.record(
                source
            )

        return recognizer.recognize_google(
            audio_data,
            language="en-US"
        )

    except Exception:

        return None


# ============================================================
# TEXT TO SPEECH
# ============================================================

def text_to_speech(text):

    try:

        audio = io.BytesIO()

        speech = gTTS(
            text=text[:3000],
            lang="en",
            slow=False
        )

        speech.write_to_fp(
            audio
        )

        audio.seek(0)

        return audio.getvalue()

    except Exception:

        return None


# ============================================================
# SAVE CONVERSATION
# ============================================================

def create_chat_file():

    lines = []

    lines.append(
        "KINGSBOT AI - SAVED CONVERSATION"
    )

    lines.append(
        "=" * 50
    )

    lines.append(
        "Date: "
        + CURRENT_DATE
    )

    lines.append("")

    if st.session_state.user_name:

        lines.append(
            "Name: "
            + st.session_state.user_name
        )

    if st.session_state.student_level:

        lines.append(
            "Education level: "
            + st.session_state.student_level
        )

    lines.append("")

    lines.append(
        "PERSONAL MEMORY"
    )

    lines.append(
        "-" * 40
    )

    for fact in (
        st.session_state.personal_memory
    ):

        lines.append(fact)

    lines.append("")

    lines.append(
        "CONVERSATION"
    )

    lines.append(
        "=" * 50
    )

    for message in st.session_state.messages:

        if message["role"] == "user":

            lines.append("YOU:")

        else:

            lines.append("KINGSBOT:")

        lines.append(
            message["content"]
        )

        lines.append("")

        lines.append(
            "-" * 50
        )

    return "\n".join(lines)


# ============================================================
# TITLE
# ============================================================

st.title(
    "🤖 KingsBot AI"
)

st.caption(
    "Real AI • Memory • EQ • Reasoning • Voice"
)


# ============================================================
# CONVERSATION DISPLAY
# ============================================================

for message in st.session_state.messages:

    with st.chat_message(
        message["role"]
    ):

        st.markdown(
            message["content"]
        )


# ============================================================
# VOICE ASSISTANT
# ============================================================

st.subheader(
    "🎤 Voice Assistant"
)

audio_file = st.audio_input(
    "Tap the microphone and speak",
    key="kingsbot_microphone"
)

voice_prompt = None

if audio_file:

    with st.spinner(
        "🎧 Understanding your voice..."
    ):

        voice_prompt = speech_to_text(
            audio_file
        )

    if voice_prompt:

        st.success(
            "You said: "
            + voice_prompt
        )

    else:

        st.error(
            "I couldn't understand that recording. "
            "Please try again."
        )


# ============================================================
# TEXT INPUT
# ============================================================

text_prompt = st.chat_input(
    "Ask KingsBot anything..."
)


# ============================================================
# SELECT INPUT
# ============================================================

if voice_prompt:

    prompt = voice_prompt

else:

    prompt = text_prompt


# ============================================================
# PROCESS MESSAGE
# ============================================================

if prompt:

    with st.chat_message(
        "user"
    ):

        st.markdown(
            prompt
        )

    st.session_state.messages.append(
        {
            "role": "user",
            "content": prompt
        }
    )

    with st.chat_message(
        "assistant"
    ):

        with st.spinner(
            "🧠 Thinking..."
        ):

            try:

                response = generate_response(
                    prompt
                )

            except Exception as error:

                response = (
                    "KingsBot encountered an error:\n\n"
                    + str(error)
                )

                st.session_state.source = (
                    "Error handler"
                )

                st.session_state.confidence = (
                    "Unknown"
                )

                st.session_state.reason = (
                    "An error occurred while processing "
                    "the request."
                )

        st.markdown(
            response
        )

        # ----------------------------------------------------
        # TRANSPARENCY
        # ----------------------------------------------------

        st.caption(
            "🔎 Source: "
            + st.session_state.source
        )

        st.caption(
            "📊 Confidence: "
            + st.session_state.confidence
        )

        st.caption(
            "ℹ️ "
            + st.session_state.reason
        )

        # ----------------------------------------------------
        # VOICE RESPONSE
        # ----------------------------------------------------

        with st.spinner(
            "🔊 Preparing voice..."
        ):

            audio = text_to_speech(
                response
            )

        if audio:

            st.audio(
                audio,
                format="audio/mp3"
            )

    st.session_state.messages.append(
        {
            "role": "assistant",
            "content": response
        }
    )


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.header(
        "🤖 KingsBot"
    )

    st.write(
        "Your AI assistant."
    )

    st.divider()

    # --------------------------------------------------------
    # PERSONAL MEMORY
    # --------------------------------------------------------

    st.subheader(
        "👤 Personal Memory"
    )

    if st.session_state.user_name:

        st.write(
            "Name: "
            + st.session_state.user_name
        )

    else:

        st.write(
            "Name: Not saved"
        )

    if st.session_state.student_level:

        st.write(
            "Class: "
            + st.session_state.student_level
        )

    else:

        st.write(
            "Class: Not saved"
        )

    st.write(
        "Saved facts: "
        + str(
            len(
                st.session_state.personal_memory
            )
        )
    )

    st.divider()

    # --------------------------------------------------------
    # HISTORY
    # --------------------------------------------------------

    st.subheader(
        "📚 Conversation History"
    )

    if st.session_state.messages:

        number = 0

        for message in st.session_state.messages:

            if message["role"] == "user":

                number += 1

                preview = message["content"]

                if len(preview) > 55:

                    preview = (
                        preview[:55]
                        + "..."
                    )

                st.write(
                    f"💬 {number}. {preview}"
                )

    else:

        st.write(
            "No conversations yet."
        )

    if st.session_state.messages:

        st.download_button(
            label="💾 Save conversation",
            data=create_chat_file(),
            file_name="kingsbot_conversation.txt",
            mime="text/plain"
        )

    st.divider()

    # --------------------------------------------------------
    # EQ
    # --------------------------------------------------------

    st.subheader(
        "❤️ Emotional Intelligence"
    )

    st.write(
        "Emotion: "
        + st.session_state.emotion
    )

    # --------------------------------------------------------
    # TONE
    # --------------------------------------------------------

    st.subheader(
        "🎭 Tone Adaptation"
    )

    st.write(
        st.session_state.tone
    )

    # --------------------------------------------------------
    # TRANSPARENCY
    # --------------------------------------------------------

    st.subheader(
        "🔍 Radical Transparency"
    )

    st.write(
        "Source: "
        + st.session_state.source
    )

    st.write(
        "Confidence: "
        + st.session_state.confidence
    )

    st.caption(
        st.session_state.reason
    )

    st.divider()

    # --------------------------------------------------------
    # PATTERNS
    # --------------------------------------------------------

    st.subheader(
        "🧩 Pattern Recognition"
    )

    if st.session_state.last_topic:

        st.write(
            "Current topic: "
            + st.session_state.last_topic
        )

    else:

        st.write(
            "No topic detected yet."
        )

    st.divider()

    # --------------------------------------------------------
    # FEATURES
    # --------------------------------------------------------

    st.subheader(
        "Features"
    )

    st.write("🧠 Real language model")
    st.write("🧩 Proactive glue")
    st.write("🔎 Pattern recognition")
    st.write("🧠 Multi-step reasoning")
    st.write("👤 Persistent memory")
    st.write("💬 Conversation memory")
    st.write("🎓 Primary → University")
    st.write("🧹 Ethical forgetting")
    st.write("❤️ EQ / sentiment")
    st.write("🎭 Tone adaptation")
    st.write("🔍 Radical transparency")
    st.write("🌍 General knowledge")
    st.write("📅 2026 awareness")
    st.write("🔎 Current lookup")
    st.write("🎤 Voice input")
    st.write("🔊 Voice output")
    st.write("💾 Save conversations")
    st.write("🧮 Mathematics")
    st.write("💻 Coding")
    st.write("📚 Education")
    st.write("🔬 Science")

    st.divider()

    # --------------------------------------------------------
    # CLEAR EVERYTHING
    # --------------------------------------------------------

    if st.button(
        "🗑️ Clear conversation and memory"
    ):

        st.session_state.messages = []

        st.session_state.user_name = None

        st.session_state.student_level = None

        st.session_state.personal_memory = []

        st.session_state.preferences = []

        st.session_state.topic_pattern = []

        st.session_state.emotion = "neutral"

        st.session_state.tone = (
            "Natural and friendly"
        )

        st.session_state.confidence = "Medium"

        st.session_state.source = "KingsBot"

        st.session_state.reason = (
            "Answer generated by KingsBot."
        )

        st.session_state.last_topic = None

        save_persistent_memory()

        st.rerun()

    st.divider()

    st.caption(
        "Model: Qwen2.5-0.5B-Instruct"
    )

    st.caption(
        "No Hugging Face token required."
    )
